force-app/main/default/objects/Org_Pool__c/Org_Pool__c.object-meta.xml
<CustomObject>
    <description>pooled orgs from the deployer</description>
    <label>Org Pool</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Workshop__c/Scheduled_Workshop__c.object-meta.xml
<CustomObject>
    <label>Scheduled Workshop</label>
    <pluralLabel>Scheduled Workshops</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <displayFormat>ScheduledWorkshop-{0}</displayFormat>
        <type>AutoNumber</type>
        <label>Name</label>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Workshop__c/fields/Org_Pool__c.field-meta.xml
<CustomField>
    <fullName>Org_Pool__c</fullName>
    <label>Org Pool</label>
    <referenceTo>Org_Pool__c</referenceTo>
    <relationshipLabel>Scheduled Workshops</relationshipLabel>
    <relationshipName>Scheduled_Workshops</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Workshop__c/fields/Registration_Link__c.field-meta.xml
<CustomField>
    <label>Registration Link</label>
    <type>Url</type>
    <fullName>Registration_Link__c</fullName>
</CustomField>

force-app/main/default/objects/Scheduled_Workshop__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <label>Start Time</label>
    <type>DateTime</type>
    <fullName>Start_Time__c</fullName>
</CustomField>

force-app/main/default/classes/workshopSchedule.cls
public with sharing class workshopSchedule {

    @AuraEnabled(cacheable=true)
    public static list<Scheduled_Workshop__c> getWorkshopSchedule(id poolId) {
        return [
            select
                Id, Start_Time__c, Registration_Link__c 
            from
                Scheduled_Workshop__c
            where 
                Org_Pool__c =: poolId 
                    and
                Start_Time__c >: System.Now()
                    and
                Registration_Link__c != null
            ];
    }
}