force-app/main/default/objects/Org_Pool__c/Org_Pool__c.object-meta.xml
<CustomObject>
    <description>pooled orgs from the deployer</description>
    <label>Org Pool</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Org_Pool__c/fields/Description__c.field-meta.xml
<CustomField>
    <label>Description</label>
    <type>LongTextArea</type>
    <fullName>Description__c</fullName>
    <length>131072</length>
    <description>describe the org pool (demo, workshop, product, etc)</description>
    <inlineHelpText>describe the org pool (demo, workshop, product, etc)</inlineHelpText>
</CustomField>

force-app/main/default/objects/Org_Pool__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Visible to the org pool bot</description>
    <inlineHelpText>Visible to the org pool bot</inlineHelpText>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/poolBotWorkshopFinder.cls
public with sharing class poolBotWorkshopFinder {

    public class WorkshopSearchInput {
        @InvocableVariable(required=true)
        public String SearchPhrase;
    }

    @InvocableMethod(label='Search Workshops' description='Search workshops for your phrase')
    public static list<List<Org_Pool__c>> getWorkshops(List<WorkshopSearchInput> WorkshopSearchInputs) {
        List<List<Org_Pool__c>> output = new List<List<Org_Pool__c>>();
        // List<Org_Pool__c> output = new List<Org_Pool__c>();

        // should only be one from a bot, but who knows.  It's quasi-bulkified
        for (WorkshopSearchInput input: WorkshopSearchInputs){
            // list<WorkshopSearchResults> singleList = new list<WorkshopSearchResults>();
            List<List<SObject>> searchResults = [FIND :input.SearchPhrase IN ALL FIELDS RETURNING Org_Pool__c (Id, Name, Description__c WHERE Public__c = true)];
            List<Org_Pool__c> pools = (Org_Pool__c[])searchResults[0];
            
            if (pools.isEmpty()){
                list<Org_Pool__c> all = [select Id, Name, Description__c from Org_Pool__c WHERE Public__c = true];
        		output.add(all);
            }
            output.add(pools);
        }               
        return output;
    }
}