force-app/main/default/objects/Org_Pool__c/Org_Pool__c.object-meta.xml
<CustomObject>
    <description>pooled orgs from the deployer</description>
    <label>Org Pool</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Org_Pool__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <description>branch on a github repo</description>
    <inlineHelpText>branch on a github repo</inlineHelpText>
    <label>Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Org_Pool__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <label>Environment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Pre-release</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Org_Pool__c/fields/Github_User__c.field-meta.xml
<CustomField>
    <fullName>Github_User__c</fullName>
    <description>username on github (ex: mshanemc)</description>
    <inlineHelpText>username on github (ex: mshanemc)</inlineHelpText>
    <label>Github User</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Org_Pool__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <description>how many hours an org should last before it&#39;s destroyed</description>
    <inlineHelpText>how many hours an org should last before it&#39;s destroyed</inlineHelpText>
    <label>Hours</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Org_Pool__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>how many to normally keep on hand</description>
    <inlineHelpText>how many to normally keep on hand</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Org_Pool__c/fields/Repo__c.field-meta.xml
<CustomField>
    <fullName>Repo__c</fullName>
    <description>repo name on github</description>
    <externalId>true</externalId>
    <inlineHelpText>repo name on github</inlineHelpText>
    <label>Repo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temporary_Pool__c/Temporary_Pool__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Temporary Pool</label>
    <nameField>
        <displayFormat>Temporary Pool-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temporary Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Temporary_Pool__c/fields/Org_Pool__c.field-meta.xml
<CustomField>
    <fullName>Org_Pool__c</fullName>
    <label>Org Pool</label>
    <referenceTo>Org_Pool__c</referenceTo>
    <relationshipLabel>Temporary Pools</relationshipLabel>
    <relationshipName>Temporary_Pools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Temporary_Pool__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>How many orgs should there be ready for your users</description>
    <inlineHelpText>How many orgs should there be ready for your users</inlineHelpText>
    <label>Quantity</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Temporary_Pool__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>when do you need the orgs to be ready (workshop start time)?</description>
    <inlineHelpText>when do you need the orgs to be ready (workshop start time)?</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/poolsRestApi.cls
@RestResource(urlMapping='/pools/*')
global with sharing class poolsRestApi {

    @HttpGet
    global static void getPools() {

        RestRequest req = RestContext.request;
        RestContext.response.addHeader('Content-Type', 'application/json');
        String environment = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(actualWork(environment)));
    }

    global static list<ReturnShape> actualWork(string environment){
        List<Org_Pool__c> pools = [SELECT Hours__c, Quantity__c, Github_User__c, Repo__c, Branch__c,
        (select Quantity__c from Temporary_Pools__r where Start_Time__c = TODAY OR Start_Time__c = TOMORROW)
        FROM Org_Pool__c
        WHERE environment__c = :environment];

        list<ReturnShape> output = new list<ReturnShape>();

        for (Org_Pool__c pool:pools){
            system.debug(pool);
            ReturnShape item = new ReturnShape();
            item.user = pool.Github_User__c;
            item.repo = pool.Repo__c;
            item.branch = pool.Branch__c;
            item.lifeHours = integer.valueOf(pool.Hours__c);
            integer quantity = integer.valueOf(pool.Quantity__c);
            // item.quantity =

            for (Temporary_Pool__c temp:pool.Temporary_Pools__r){
                system.debug(temp);
                quantity = quantity + integer.valueOf(temp.Quantity__c);
                system.debug('quantity is ' + quantity);
            }

            item.quantity = quantity;
            output.add(item);
        }

        return output;
    }

    global class ReturnShape {
        string user {get;set;}
        string repo {get;set;}
        string branch {get;set;}
        integer quantity {get;set;}
        integer lifeHours {get;set;}
    }

}

// testing scripts
// system.debug(poolsRestApi.actualWork('Production'));